### ISSUE TITLE
Use a better communication framework than plain MPI

### ISSUE THREAD

**Issue by slizzered** [ComputationalRadiationPhysics/haseongpu#17]
The next big thing: https://github.com/ComputationalRadiationPhysics/genericCommunicator
It's awesome and shiny :sparkles:

**Comment by erikzenker** [comment]
The project was renamed to [GrayBat](https://github.com/ComputationalRadiationPhysics/graybat) and had its first release.

**Comment by bussmann** [comment]
I like it ☺

**Comment by slizzered** [comment]
done through #58
