### ISSUE TITLE
 continuous integration

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/haseongpu#25]
To protect the application of compile and runtime error a continuous integration platform should be used:

* https://travis-ci.org/   <== we have some experience with this one
* http://jenkins-ci.org/  <== has several operating systems to test on
* http://hudson-ci.org/ <== is predecessor of jenkins

**Comment by slizzered** [comment]
Update on the matter:
I started working on a `.travis.yml` file for TravisCI, but they are still stuck at Ubuntu 12.04, which ships CUDA 4.0 (not sufficient for our needs)

I just found https://snap-ci.com/ and will give it a look

**Comment by erikzenker** [comment]
I am trying to deploy [drone.io](https://github.com/drone/drone)
on a local machine. It is a docker based CI platform and can be
selfhosted.

**Comment by slizzered** [comment]
nice, thanks.

snap-ci.com ist not the right tool for us (only offers a free trial)

In case the local machine is not sufficient, I can use some of my github-student pack to purchase a server at digitalocean.com. There we could put either drone.io or jenkins in place. My trial there can last up to 20 months, which would be long enough to wait for travis-ci.org to get their stuff sorted out.

**Comment by erikzenker** [comment]
drone.io is deployed on a local machine and capable of building HASEonGPU. Now we need to setup a server with the prepared archlinux docker image and its done.

**Comment by ax3l** [comment]
you can just add the hook since you have admin access to this repo (hooks added by now).
