### ISSUE TITLE
Error: Kernel launches from templates are not allowed in system files

### ISSUE THREAD

**Issue by slizzered** [ComputationalRadiationPhysics/haseongpu#26]
``` c++
/opt/pkg/devel/cuda/5.5/include/thrust/system/cuda/detail/detail/launch_closure.inl(86): error: kernel launches from templates are not allowed in system files
```

This error is caused by some weird behaviour inside the path lookup. **It can be fixed** by unsetting the environment variable `CPLUS_INCLUDE_PATH`.
In a standard linux shell, just execute this command before building:

``` bash
unset CPLUS_INCLUDE_PATH
```

More information:
https://code.google.com/p/thrust/issues/detail?id=359#c5

This is more of a build issue / related to other libraries and not our code itself. Therefore, no real fix will be provided (but maybe some workaround will be done in the build script)

**Comment by ax3l** [comment]
This should not be a problem anymore in CUDA 6.5+

related: https://gitlab.kitware.com/cmake/cmake/issues/16464
