### ISSUE TITLE
CMake: Separate compilation + C++11 support

### ISSUE THREAD

**Issue by erikzenker** [ComputationalRadiationPhysics/haseongpu#56]
This is the next step to compile our c++-only files with a compiler
of our choice and to support also C++11 features. This is necessary
since the next communication library of our choice (see #17) needs
c++11 support.

A mock up of a CMakeLists.txt is shown [here](https://gist.github.com/erikzenker/713c4ff76949058d5d5d)

**Comment by slizzered** [comment]
closed with #57
