### ISSUE TITLE
Output is not written, if the folder does not exist

### ISSUE THREAD

**Issue by slizzered** [ComputationalRadiationPhysics/haseongpu#7]
Although this is described in the documentation, this could be handled better.
We should try to create these folders, in case they do not exist.

(Mostly relevant for writing vtk-files, so this is related to #1)

**Comment by slizzered** [comment]
Since https://github.com/ComputationalRadiationPhysics/haseongpu/commit/f6c9f761a98688d0055e15f96b52504b28786861 the code does actually complain and stop if the folder does not exist. Should we instead auto-create the folder and continue working (would be a nicer experience for the user)

**Comment by erikzenker** [comment]
In my opinion we should print some very clear error message like I mentioned in #72.
Something like : 

`The specified output path does not exist (or permission denied) please specify a correct path by --output-path=[path]`

A user should be able to create some output folder.

**Comment by slizzered** [comment]
Ok, so just a clear error message, no auto-creation. In that case, I would also like to remove/change the default value for the output folder. Currently, the default folder is "output", but if it is not auto-created, then there is no real reason for it, right? (and we have config files now, so the use can specify it).

Alternatively, we could set the default output-folder to `.`. This way, the code is still executed, but files are just produced on the current location. Quite a lot of unix tools do that, so it might be acceptable.

**Comment by slizzered** [comment]
In this case, the clear error message would still be useful, if the user specified some invalid path

**Comment by erikzenker** [comment]
Currently the programm produces a lot of output files, thus, just using the `.` folder would somehow trash the root directory. It would be another situation if we would have some nice output format like
hdf5 or openPMD (see #54).

I would suggest to force the user to specify an output directory.

**Comment by slizzered** [comment]
I completely agree. nice that everything is done now :)
