### ISSUE TITLE
Group related parameters together to get a smaller interface

### ISSUE THREAD

**Issue by slizzered** [ComputationalRadiationPhysics/haseongpu#9]
The current situation with 15+ parameters is extremely error-prone and a general pain.

Something like 5 objects/structs would be perferable

**Comment by slizzered** [comment]
Ideas to split (can be discarded if nobody likes it :camel: )
 - geometrical parameters (mesh layout stuff, some of it might be auto-generated with #11, this could also be part or subclass of the physical parameters, see next section)
 - physical parameters (physical things that can influence the results)
  - wavelenghts
  - reflections (yes/no)
  - refractive indices
  - mse-threshold
  - debug-verbosity
  - write-vtk (if we include again)
  - **...**
 - computation-related parameters that are not really related to the result values 
  - parallel-mode
  - device-mode
  - input-folders
  - repetitions (number of repetions should only influence the speed, since correctness is done through MSE)
  - minRays/maxRays
  - ngpus
  - **...**

**Comment by erikzenker** [comment]
I introduced 3 new types:

* ExperimentParameters ...contains parameters which influence experiment results
* ComputeParameters ...contains parameters which control computation
* Results ...contains results from the computations

Furthermore, I would leave the Mesh type as it is

* Mesh ...contains mesh related data

**Comment by slizzered** [comment]
sounds great!

**Comment by slizzered** [comment]
When this thing is ready, I would like to work on #10. This is probably going to work pretty well together. The structure of the config file can be closely related to the structs.

**Comment by erikzenker** [comment]
The work is finished to the point that we need to decide which kind of parallel and device mode we still want to support. I would sugest to put all this kind of logic into graybat, since graybat will be our future concurrent computation framework. 

The present situation is that graybat supports mpi, but i am planing zmq und thread support. Thus, there is no need anymore to provide several parallel hooks into the calcPhiAse function. Nevertheless, Thread support is very important, because we can not assume that some user has mpi (or can we?). Opinions ?

**Comment by slizzered** [comment]
So, basically you want to move the parallel mode to compile time (GrayBat does all things at compile time, right?). That is fine with me in general :)

Personally, I would not drop threaded mode until there is a replacement in GrayBat (testing on my home machine is usually done in threaded mode).

**Proposal**: Leave the threaded parallel-modes threaded and mpi for a while
Effects:
 - We can benchmark GrayBat against the other modes easily
 - Less code changes in Matlab stuff (can be it's own pull request that changes all to GrayBat before we throw out the other modes)

In the long run, there will be a GrayBat threaded model and we do not have to assume that the user has MPI.

**Comment by slizzered** [comment]
closed through #58
